// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQRB8XAlHgmulcT9zfFZbfvhALx2-mULU',
    appId: '1:740040895467:web:d659358150c4e5941b87ae',
    messagingSenderId: '740040895467',
    projectId: 'tirews-d7184',
    authDomain: 'tirews-d7184.firebaseapp.com',
    storageBucket: 'tirews-d7184.firebasestorage.app',
    measurementId: 'G-10CZ58EHY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46hx-lzJokxikfKJacDx6oWAGHWptsvU',
    appId: '1:740040895467:android:1c903d622b32fe7f1b87ae',
    messagingSenderId: '740040895467',
    projectId: 'tirews-d7184',
    storageBucket: 'tirews-d7184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsT711yxP5PQFh2DW_jOvjRaz2pwTy3b4',
    appId: '1:740040895467:ios:f699c5531a5ae31b1b87ae',
    messagingSenderId: '740040895467',
    projectId: 'tirews-d7184',
    storageBucket: 'tirews-d7184.firebasestorage.app',
    iosBundleId: 'com.example.andresShopWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsT711yxP5PQFh2DW_jOvjRaz2pwTy3b4',
    appId: '1:740040895467:ios:f699c5531a5ae31b1b87ae',
    messagingSenderId: '740040895467',
    projectId: 'tirews-d7184',
    storageBucket: 'tirews-d7184.firebasestorage.app',
    iosBundleId: 'com.example.andresShopWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRB8XAlHgmulcT9zfFZbfvhALx2-mULU',
    appId: '1:740040895467:web:dd5e0915c6afc55e1b87ae',
    messagingSenderId: '740040895467',
    projectId: 'tirews-d7184',
    authDomain: 'tirews-d7184.firebaseapp.com',
    storageBucket: 'tirews-d7184.firebasestorage.app',
    measurementId: 'G-LNEZS0P234',
  );
}
